[host]
username = "<VPS `username`>"
password = "<VPS `password`>"

[django]
secret-key = "<Django `SECRET_KEY`>"

[tencent-cloud]
app-id = "<Tencent Cloud `APPID`>"
secret-id = "<Tencent Cloud `SecretId`>"
secret-key = "<Tencent Cloud `SecretKey`>"

[aliyun]
role-arn = "<Alibaba Cloud `Role ARN`>"
access-key-id = "<Alibaba Cloud `AccessKey ID`>"
access-key-secret = "<Alibaba Cloud `AccessKey Secret`>"
